### ISSUE TITLE
Install Issues Through Docker Container

### ISSUE THREAD

**Issue by LaunchedBerry07** [padloc/padloc#295]
Hi!

Is the how-to article published on the website still up to date?

**Comment by MaKleSoft** [comment]
It should be, yes. what issues are you facing?

**Comment by LaunchedBerry07** [comment]
### LOG:

lerna notice cli v3.22.1,
lerna notice filter including "@padloc/server",
lerna info filter [ '@padloc/server' ],
lerna info Executing command in 1 package: "npm run start",
lerna ERR! npm run start exited 1 in '@padloc/server',
lerna ERR! npm run start stdout:,
,
> @padloc/server@3.1.3 start,
> ts-node src/init.ts,
,
,
lerna ERR! npm run start stderr:,
,
/padloc/packages/server/node_modules/ts-node/src/index.ts:261,
    return new TSError(diagnosticText, diagnosticCodes),
           ^,
TSError: ⨯ Unable to compile TypeScript:,
src/billing.ts(67,54): error TS2339: Property 'payment_intent' does not exist on type 'string | IInvoice'.,
  Property 'payment_intent' does not exist on type 'string'.,
src/billing.ts(107,60): error TS2339: Property 'paid' does not exist on type 'string | IInvoice'.,
  Property 'paid' does not exist on type 'string'.,
src/billing.ts(107,83): error TS2339: Property 'id' does not exist on type 'string | IInvoice'.,
  Property 'id' does not exist on type 'string'.,
,
    at createTSError (/padloc/packages/server/node_modules/ts-node/src/index.ts:261:12),
    at getOutput (/padloc/packages/server/node_modules/ts-node/src/index.ts:367:40),
    at Object.compile (/padloc/packages/server/node_modules/ts-node/src/index.ts:558:11),
    at Module.m._compile (/padloc/packages/server/node_modules/ts-node/src/index.ts:439:43),
    at Module._extensions..js (node:internal/modules/cjs/loader:1112:10),
    at Object.require.extensions.<computed> [as .ts] (/padloc/packages/server/node_modules/ts-node/src/index.ts:442:12),
    at Module.load (node:internal/modules/cjs/loader:948:32),
    at Function.Module._load (node:internal/modules/cjs/loader:789:14),
    at Module.require (node:internal/modules/cjs/loader:972:19),
    at require (node:internal/modules/cjs/helpers:88:18),
npm ERR! code 1,
npm ERR! path /padloc/packages/server,
npm ERR! command failed,
npm ERR! command sh -c ts-node src/init.ts,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /root/.npm/_logs/2020-11-01T21_51_52_051Z-debug.log,
,
lerna ERR! npm run start exited 1 in '@padloc/server',
npm ERR! code 1,
npm ERR! path /padloc,
npm ERR! command failed,
npm ERR! command sh -c lerna run --scope '@padloc/server' start,
,
npm ERR! A complete log of this run can be found in:,
npm ERR!     /root/.npm/_logs/2020-11-01T21_51_52_080Z-debug.log,

**Comment by LaunchedBerry07** [comment]
And here is my docker-compose file:

version: "3"
services:
    server:
        image: padloc/server
        container_name: padloc-server
        ports:
            - ${PL_SERVER_PORT:-4000}:5300
        volumes:
            - ${PL_DB_DIR:-./db}:/data
            - ${PL_ATTACHMENTS_DIR:-./attachments}:/docs
        environment:
            - PL_PWA_URL
            - PL_EMAIL_SERVER
            - PL_EMAIL_PORT
            - PL_EMAIL_USER
            - PL_EMAIL_PASSWORD
            - PL_EMAIL_FROM
    pwa:
        image: padloc/pwa
        container_name: padloc_pwa
        ports:
            - ${PL_PWA_PORT:-8008}:5080
        volumes:
            - ${PL_PWA_DIR:-./pwa}:/pwa
        environment:
            - PL_SERVER_URL

**Comment by LaunchedBerry07** [comment]
And here is my env file:

# GENERAL SETTINGS
# ================
# URL that will resolve to the server instance
PL_PWA_URL=http://padloc.luminousburst.cloud
# URL that will resolve to the web app
PL_SERVER_URL=http://padloc.luminousburst.cloud/server/

# SERVER SETTINGS
# ===============
# Port the server instance will listen on
PL_SERVER_PORT=4000
# Directory where database files will be stored
PL_DB_DIR=./db
# Directory where attachment files will be stored
PL_ATTACHMENTS_DIR=./attachments

# PWA SETTINGS
# ============
# Port the web app will be served from
PL_PWA_PORT=8008
# Directory where the static code for the web app will be stored
PL_PWA_DIR=./pwa

# EMAIL SETTINGS
# =============
# SMTP host
PL_EMAIL_SERVER=smtp.ionos.com
# SMTP username
PL_EMAIL_USER=admin@luminousburst.cloud
# SMTP port
PL_EMAIL_PORT=587
# SMTP password
PL_EMAIL_PASSWORD=0v3rTh3Ra!nb0w
# Always use TLS when sending emails
PL_EMAIL_SECURE=true

# SSL SETTINGS
# ============
# The path to your ssl certificate
# PL_SSL_CERT=./ssl/cert.pem
# The path to your ssl private key
# PL_SSL_KEY=./ssl/key.pem
# Advanced configuration file
# PL_SSL_CONF=./ssl/ssl.conf

**Comment by LaunchedBerry07** [comment]
And here is my env file:

PL_PWA_URL=http://padloc.luminousburst.cloud
PL_SERVER_URL=http://padloc.luminousburst.cloud/server/
PL_SERVER_PORT=4000
PL_DB_DIR=./db
PL_ATTACHMENTS_DIR=./attachments
PL_PWA_PORT=8008
PL_PWA_DIR=./pwa
PL_EMAIL_SERVER=smtp.ionos.com
PL_EMAIL_USER=admin@luminousburst.cloud
PL_EMAIL_PORT=587
PL_EMAIL_PASSWORD=secret
PL_EMAIL_SECURE=true

**Comment by dionysiusmarquis** [comment]
I'm also not able to start a docker container with the `latest` image. I'm getting a JSON parse error on startup. Seems to be this missing comma here: https://github.com/padloc/padloc/blob/master/packages/locale/res/translations/pl.json#L921

**Comment by MaKleSoft** [comment]
@dionysiusmarquis Good catch! Should be fixed now. Can you also reproduce @LaunchedBerry07's error?

**Comment by dionysiusmarquis** [comment]
Yep, both `server` and `pwa` throwing TypeScript errors. I also got @LaunchedBerry07's
Additionally on `pwa`:
```shell
> npm run build && npm start
> @padloc/pwa@3.1.3 build
k
   376 modules
ERROR in /padloc/packages/app/src/sw.ts
[tsl] ERROR in /padloc/packages/app/src/sw.ts(3,15)
      TS2451: Cannot redeclare block-scoped variable 'workbox'.
ERROR in /padloc/packages/app/src/sw.ts
[tsl] ERROR in /padloc/packages/app/src/sw.ts(8,9)
     TS2339: Property 'routing' does not exist on type 'typeof import("/padloc/node_modules/@types/workbox-sw/index")'.
ERROR in /padloc/packages/app/src/sw.ts
[tsl] ERROR in /padloc/packages/app/src/sw.ts(8,49)
      TS2339: Property 'precaching' does not exist on type 'typeof import("/padloc/node_modules/@types/workbox-sw/index")'.
lerna ERR! npm run build_and_start stderr:
```

**Comment by MaKleSoft** [comment]
@dionysiusmarquis @LaunchedBerry07 Can you guys verify that @dome4's PR fixed the remaining issues?

**Comment by dionysiusmarquis** [comment]
`pwa` works for me now. `server` still throws these TS errors:
```shell
> ts-node src/init.ts


lerna ERR! npm run start stderr:

/padloc/packages/server/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/billing.ts(67,54): error TS2339: Property 'payment_intent' does not exist on type 'string | IInvoice'.
  Property 'payment_intent' does not exist on type 'string'.
src/billing.ts(107,60): error TS2339: Property 'paid' does not exist on type 'string | IInvoice'.
  Property 'paid' does not exist on type 'string'.
src/billing.ts(107,83): error TS2339: Property 'id' does not exist on type 'string | IInvoice'.
  Property 'id' does not exist on type 'string'.

    at createTSError (/padloc/packages/server/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/padloc/packages/server/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/padloc/packages/server/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/padloc/packages/server/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
    at Object.require.extensions.<computed> [as .ts] (/padloc/packages/server/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (node:internal/modules/cjs/loader:948:32)
    at Function.Module._load (node:internal/modules/cjs/loader:789:14)
    at Module.require (node:internal/modules/cjs/loader:972:19)
    at require (node:internal/modules/cjs/helpers:88:18)
npm ERR! code 1
npm ERR! path /padloc/packages/server
npm ERR! command failed
npm ERR! command sh -c ts-node src/init.ts
```

**Comment by dome4** [comment]
@dionysiusmarquis it seems to be a compiling issue with typescript but I didn't get how and why the type `null | IInvoice` of `latest_invoice` is transformed to `string | IInvoive`. Simply adding two ts-ignores fixes the issue for me but isn't a real solution (see https://github.com/dome4/padloc/commit/b6fdd341eead4e482d90fb6cc7406523dc6824c1).

**Comment by MaKleSoft** [comment]
Hm, looks like you have different typings for the stripe module. Can you check which version you have installed?

```
cd packages/server
npm list @types/stripe
```

**Comment by dome4** [comment]
For me it's `6.26.5` as stated in package.json of the server package. The referenced type is also `null | IInvoice` but somehow it gets transformed to `string | IInvoive` while compiling the ts code. I didn't get it either what's going on in detail.

**Comment by dionysiusmarquis** [comment]
For me it looks like you either need to test against `string` beforehand or specifically cast `payment_intent` etc. (If you are sure it will never be of type `string`)
Maybe something like
```ts
const payment = (latest_invoice as IInvoice)?.payment_intent;
```
could do the trick here.

**Comment by MaKleSoft** [comment]
@dome4 Hm, that's really weird. I have the same version yet I don't get those errors. Conincidentally there is in fact a newer version of the typings where type is `null |string | IInvoive`. Is it possible you have a different version installed globally?

**Comment by MaKleSoft** [comment]
@dionysiusmarquis Yep, that would do the trick. But I wanna figure out where the mismatch of the typings comes from before using that workaround.

**Comment by dionysiusmarquis** [comment]
If I understand it correctly will either be a string or an `object`/`IInvoive`.
https://stripe.com/docs/api/subscriptions/object#subscription_object-latest_invoice
It will only be on `object`/`IInvoive` if it's requested as "expended"
https://stripe.com/docs/api/expanding_objects
So if you know that it will always be requested as expanded than casting explicit should be save. If the string variant is also possible you would have to implement the string variant.

**Comment by MaKleSoft** [comment]
@dionysiusmarquis Your assessment is correct 😉   What is puzzling to me is that you did get those errors in the first place since the typings should be pinned at v6.26.5. Anyway, I've updated the typings and fixed the error. Let me know if you're still seeing issues.

**Comment by dionysiusmarquis** [comment]
I see, strange indeed 🤔 
But it's up and running again 🎉
